//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinhV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Phieu_Tra
    {
        public int ID { get; set; }
        public string ID_TaiLieu { get; set; }
        public string ID_PhieuTra { get; set; }
        public int ID_NguoiNhan { get; set; }
        public int Count_ { get; set; }
        public System.DateTime NgayTra { get; set; }
        public string Trang_Thai_Tra { get; set; }
    }
}
