//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinhV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Độc_Giả_Vi_Phạm
    {
        public int ID_Xử_Phạt { get; set; }
        public string ID_Độc_Giả { get; set; }
        public int ID_Nguoi_Xu_Phat { get; set; }
        public string Li_do_xu_phat { get; set; }
        public string Hinh_thuc_xu_phat { get; set; }
        public System.DateTime Ngay_xu_phat { get; set; }
        public string GhiChu { get; set; }
    }
}
