//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormChinhV1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Độc_giả
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Độc_giả()
        {
            this.Phieu_Muon_Tra = new HashSet<Phieu_Muon_Tra>();
        }
    
        public string ID_ĐG { get; set; }
        public string Name_ĐG { get; set; }
        public Nullable<System.DateTime> Birth { get; set; }
        public Nullable<bool> Gender { get; set; }
        public string DiaChi { get; set; }
        public string PhoneNumber { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Phieu_Muon_Tra> Phieu_Muon_Tra { get; set; }
    }
}
